<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DeltaNetcode</AssemblyName>
    <PackageId>DeltaNetcode</PackageId>
    <Version>0.0.6</Version>
    <Description>Engine-independent networking for .NET applications.</Description>
    <PackageTags>networking;netcode;high-performance</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RootNamespace>Delta.Netcode</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DeltaNetcode.Generators/DeltaNetcode.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="../DeltaNetcode.CodeFixes/DeltaNetcode.CodeFixes.csproj"
                      ReferenceOutputAssembly="false" />
    <None Include="$(MSBuildProjectDirectory)/../../README.md"
          Pack="true"
          PackagePath="README.md"
          Visible="false" />
    <None Include="../DeltaNetcode.Generators/bin/$(Configuration)/netstandard2.0/DeltaNetcode.Generators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
    <None Include="../DeltaNetcode.CodeFixes/bin/$(Configuration)/netstandard2.0/DeltaNetcode.CodeFixes.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>
</Project>
